# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

pod 'MBProgressHUD', '~> 0.9.1'
pod 'SDWebImage', '~>3.7'
pod 'AFNetworking', '~> 2.6'
pod 'KontaktSDK'
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_STRICT_OBJC_MSGSEND'] = "NO"
            config.build_settings['ENABLE_BITCODE'] = "NO"
        end
    end
end

