# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

pod 'QRCodeReaderViewController', '~> 4.0.1'
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_STRICT_OBJC_MSGSEND'] = "NO"
            config.build_settings['ENABLE_BITCODE'] = "NO"
        end
    end
end

